server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: urbankicks
  datasource:
    url: jdbc:mysql://localhost:3306/urbankicks2.0?createDatabaseIfNotExist=true
    username: root
    password: ChangeMe@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


